### ISSUE TITLE
Avoid new Guid().ToString()

### ISSUE THREAD

**Issue by danneforslund** [ziyasal/Owin.Security.RedisTokenProviders#8]
Great repository and examples!

I would however strongly advise against the use of `new Guid().ToString()`, in the example to `Guid.NewGuid().ToString()`.

I.e. in in Startup.Auth.cs.
`RefreshTokenGenerator = () => new Guid().ToString()`

Else, `new Guid().ToString()` will produce a guid of 00000000-0000-0000-0000-000000000000 that will be used in `RedisRefreshTokenProvider.CreateAsync`, which in conjuction with the Owin `OAuthAuthorizationServerOptions`, will leak the same (zero:ed) refresh token to multiple users, hence handing out access tokens to other users.

I know it's just an example, but this might prevent bad things from happening.

**Comment by bugthesystem** [comment]
Hi @sledgas, thanks for heads-up, fixed 👍
